apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: example-nginx
spec:        
  replicas: 3         
  selector:
    matchLabels:
      app: example-nginx
  template:
    metadata:
      labels:
        app: example-nginx
    spec:
      containers:
      - name: nginx
        image: "nginx:latest"
        imagePullPolicy: IfNotPresent
        command: [ "/usr/sbin/nginx", "-g", "daemon off;" ]
        ports:
        - containerPort: 80
          hostPort: 9003
